# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Assessment(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Assessment - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'assessment_id': 'str',
            'data': 'Data',
            'status': 'str'
        }

        self.attribute_map = {
            'assessment_id': 'assessmentId',
            'data': 'data',
            'status': 'status'
        }

        self._assessment_id = None
        self._data = None
        self._status = None

    @property
    def assessment_id(self):
        """
        Gets the assessment_id of this Assessment.


        :return: The assessment_id of this Assessment.
        :rtype: str
        """
        return self._assessment_id

    @assessment_id.setter
    def assessment_id(self, assessment_id):
        """
        Sets the assessment_id of this Assessment.


        :param assessment_id: The assessment_id of this Assessment.
        :type: str
        """
        self._assessment_id = assessment_id

    @property
    def data(self):
        """
        Gets the data of this Assessment.


        :return: The data of this Assessment.
        :rtype: Data
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this Assessment.


        :param data: The data of this Assessment.
        :type: Data
        """
        self._data = data

    @property
    def status(self):
        """
        Gets the status of this Assessment.


        :return: The status of this Assessment.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this Assessment.


        :param status: The status of this Assessment.
        :type: str
        """
        self._status = status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

